title: Pierre Brasseur Sociologue
description: Site internet de Pierre Brasseur
theme: just-the-docs

url: https://brasseurp.github.io/site/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
